
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lridcsbwttwnwzyqzzde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyaWRjc2J3dHR3bnd6eXF6emRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTkwMTgsImV4cCI6MjA1OTE3NTAxOH0.5XFmDGoDA42zpYMPIJZpcj5MI02BiZ7clvT5leeSwXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
